[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["g", "."]
run = "cd ~/.dotfiles"
desc = "navigates to dotfiles directory"
